import { ThemeProviderWrapper } from '../components/ThemeProviderWrapper';
import { AuthProvider } from '../context/useAuthContext';
import { AuthModal } from '../components/User/AuthModal';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import './globals.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ThemeProviderWrapper>
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
            <AuthModal />
          </ThemeProviderWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
